# Generated by Django 6.0.3 on 2026-03-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Boi')),
                ('brinco_id', models.CharField(max_length=50, unique=True, verbose_name='ID/Brinco')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição (Opcional)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColetaSemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateField(verbose_name='Data da Coleta')),
                ('nivel_atividade', models.CharField(choices=[('inativo', 'Inativo (0%)'), ('baixo', 'Baixo (< 30%)'), ('regular', 'Regular (30% - 60%)'), ('bom', 'Bom (60% - 80%)'), ('excelente', 'Excelente (> 80%)')], max_length=20, verbose_name='Nível de Atividade')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('boi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coletas', to='veterinaria.boi')),
            ],
        ),
        migrations.CreateModel(
            name='FotoBoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_bois/')),
                ('boi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='veterinaria.boi')),
            ],
        ),
    ]
