# Generated by Django 6.0.3 on 2026-03-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coletasemen',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
        migrations.AddField(
            model_name='coletasemen',
            name='quantidade_doses',
            field=models.IntegerField(default=0, verbose_name='Quantidade em Estoque (Doses/Palhetas)'),
        ),
        migrations.AlterField(
            model_name='coletasemen',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
