# Generated by Django 6.0.3 on 2026-03-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_coletasemen_data_validade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boi',
            name='circunferencia_escrotal',
            field=models.FloatField(blank=True, null=True, verbose_name='Circunferência Escrotal (cm)'),
        ),
        migrations.AddField(
            model_name='boi',
            name='data_exame_andrologico',
            field=models.DateField(blank=True, null=True, verbose_name='Último Exame Andrológico'),
        ),
        migrations.AddField(
            model_name='boi',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='boi',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização/Lote'),
        ),
        migrations.AddField(
            model_name='boi',
            name='peso',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso Atual (kg)'),
        ),
        migrations.AddField(
            model_name='boi',
            name='raca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Raça'),
        ),
        migrations.AddField(
            model_name='boi',
            name='registro_genealogico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registro (Pedigree)'),
        ),
        migrations.AddField(
            model_name='boi',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo (Em Coleta)'), ('descanso', 'Em Descanso'), ('aposentado', 'Aposentado'), ('obito', 'Óbito')], default='ativo', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='boi',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
