# Generated by Django 6.0.3 on 2026-03-17 13:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0003_boi_circunferencia_escrotal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaSemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField(default=datetime.date.today, verbose_name='Data da Saída')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade de Doses')),
                ('motivo', models.CharField(choices=[('inseminacao', 'Uso Próprio (Inseminação)'), ('venda', 'Venda para Terceiros'), ('descarte', 'Descarte/Perda')], max_length=20, verbose_name='Motivo da Saída')),
                ('destino', models.CharField(blank=True, max_length=100, null=True, verbose_name='Destino (Ex: Fazenda X, Vaca #123)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='veterinaria.coletasemen')),
            ],
        ),
    ]
