# Generated by Django 6.0.3 on 2026-03-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0004_saidasemen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coletasemen',
            name='nivel_atividade',
        ),
        migrations.AddField(
            model_name='coletasemen',
            name='lote',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Código do Lote'),
        ),
        migrations.AddField(
            model_name='coletasemen',
            name='motilidade',
            field=models.IntegerField(default=0, help_text='Ex: 80', verbose_name='Motilidade Progressiva (%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coletasemen',
            name='motilidade_pos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Motilidade Pós-Descongelamento (%)'),
        ),
        migrations.AddField(
            model_name='coletasemen',
            name='vigor',
            field=models.IntegerField(default=0, help_text='Ex: 4', verbose_name='Vigor (0 a 5)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coletasemen',
            name='vigor_pos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vigor Pós-Descongelamento (0 a 5)'),
        ),
        migrations.AlterField(
            model_name='saidasemen',
            name='destino',
            field=models.CharField(default='Sem destino', max_length=150, verbose_name='Destino / Transporte (Ex: Botijão 04 - Fazenda X)'),
            preserve_default=False,
        ),
    ]
